### PR TITLE
feat: add default timout to `cache_memoize`

### PR DESCRIPTION
**Pull request by EmberCraze**
In some cases, you do not want to specify the timout for all the definitions and want the method to use the django defult cache timeout instead.

### CODE REVIEW

**Comment by EmberCraze** [comment]
This is the same change as #46 but with the latest master as that PR is stale

**Comment by peterbe** [comment]
Do you think it's worth mentioning this in the README? 
Perhaps as a code comment in the first Usage example?

**Comment by peterbe** [comment]
I [updated the tox test to use 3.12](https://github.com/peterbe/django-cache-memoize/commit/4e834dd6b4c8a71a4cd93fee4455f39d62640b64), also. 
Can you merge in latest `master` to your branch?

**Comment by peterbe** [comment]
Since I don't work on Python projects any more I'm very rusty at PyPI stuff. 
But I think https://pypi.org/project/django-cache-memoize/ should have this fix in it.

**Comment by EmberCraze** [comment]
Oh, sorry for the delay. Yeah, this is kind of an expected behavior.

**Pull request merged**
