### PR TITLE
feat: adds extra cache key components support

### PR DESCRIPTION
**Pull request by pySilver**
_I was surprised to find my own ticket here haha :)_ 

This feature allows to bind our memoized functions with external state. Extra argument can be anything json-serializable or even callable.

```python
@cache_memoize(60, extra=('foo', obj.pk, foo.last_updated_at))
def foo(*args, **kwargs):
    return 42

@cache_memoize(100, extra={"version": 2})
def callmeonce(arg1):
    print(arg1)

@cache_memoize(100, extra=100500)
def callmeonce(arg1):
    print(arg1)

@cache_memoize(100, extra=lambda user: user.is_staff)
def callmeonce(user):
    print(arg1)
```

Originally requested at #49 (solves #35 )

### CODE REVIEW

**Comment by pySilver** [comment]
Can we merge it?

**Comment by pySilver** [comment]
@peterbe :) kind reminder about PR. It contains tests and it is fully BC.

**Comment by peterbe** [comment]
> @peterbe :) kind reminder about PR. It contains tests and it is fully BC.

Sure! Can you merge in latest `main` and that should start the CI suites.

**Comment by pySilver** [comment]
@peterbe Oh I've missed your reply. I've just synced master branch with this PR

**Pull request merged**
