### PR TITLE
Add `cache_alias` kwarg to allow using non-default cache

### PR DESCRIPTION
**Pull request by benspaulding**
Thank you for this project. It is well written, documented, and tested, which made using and contributing to it simple. 🙇 

I found a case in my application where being able to use a non-default cache was necessary. Is this a feature you would like to have?

### CODE REVIEW

**Comment by benspaulding** [comment]
For some reason [the build failed with Python 3.4](https://travis-ci.org/peterbe/django-cache-memoize/builds/325566125), but I think Travis or some other piece was just having problems. It took a few rebuilds, but eventually it worked [for me](https://travis-ci.org/benspaulding/django-cache-memoize/builds/325592635).

**Comment by fcurella** [comment]
I'd be interested in this feature too :)

**Comment by peterbe** [comment]
I am so sorry for having missed this. I most have missed the notification. 
To prevent this from happening more in the future I've enabled Email notifications for all watched repos.

**Comment by peterbe** [comment]
https://pypi.org/project/django-cache-memoize/0.1.2/ released.

**Pull request merged**
